export const API_ENDPOINTS = {
  LOGIN: "/users/login",
  REGISTER: "/users/register",
  REFRESH_TOKEN: "/users/refresh-token",
  VERIFY_EMAIL: "/users/email-verify",
  FORGOT_PASSWORD: "/users/forgot-password",
  VERIFY_FORGOT_PASSWORD: "/users/forgot-password-verify",
  RESET_PASSWORD: "/users/reset-password",
  LOG_OUT: "/users/logout",
  UPLOAD_IMAGE: "/medias/upload-image",
  UPLOAD_VIDEO: "/medias/upload-video",
  CROP_VIDEO: "/medias/crop-video",
  GET_POSTS: "/posts",
  GET_POST: "/posts/",
  CREATE_POST: "/posts",
  GET_COMMENT: "/posts",
  LIKE_POST: "/likes/posts",
  UNLIKE_POST: "/likes/posts",
  GET_PROFILE: "/users/",
  GET_ME: "/users/me",
  FOLLOW: "/users/follow",
  UNFOLLOW: "/users/follow/",
  BOOKMARK: "/bookmarks/posts",
  SUGGESTED: "/users/suggested",
  SEARCH: "/search/users",
  GET_MEDIAS: "/posts/medias",
};
