export const ROUTES = {
  HOME: "/",
  SIGN_IN: "/account/sign-in",
  SIGN_UP: "/account/sign-up",
  FORGOT_PASSWORD: "/account/forgot-password",
  RESET_PASSWORD: "/account/reset-password",
  EXPLORE: "/explore",
  REELS: "/reels",
  MESSAGE: "/message",
  POST_ID: "/post",
  EXPLORE_PEOPLE: "/explore/people",
  EDIT_PROFILE: "/settings/edit",
};
export const MOBILE_ROUTES = {
  HOME: "/mobile/",
  SIGN_IN: "/account/sign-in",
  SIGN_UP: "/account/sign-up",
  FORGOT_PASSWORD: "/account/forgot-password",
  RESET_PASSWORD: "/account/reset-password",
  EXPLORE: "/explore",
  REELS: "/reels",
  MESSAGE: "/message",
  POST_ID: "/post",
  EXPLORE_PEOPLE: "/explore/people",
  EDIT_PROFILE: "/settings/edit",
};
