import Providers from "@/components/Provider";
import "@draft-js-plugins/counter/lib/plugin.css";
import "@draft-js-plugins/emoji/lib/plugin.css";
import "@draft-js-plugins/hashtag/lib/plugin.css";
import "@draft-js-plugins/mention/lib/plugin.css";
import "draft-js/dist/Draft.css";
import "flatpickr/dist/flatpickr.css";
import "flatpickr/dist/themes/dark.css";
import type { Metadata } from "next";
import { Satisfy } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import ProtectRoute from "@/components/AuthProvider";
import withAuth from "@/HOC/withAuth";

const satisfy = Satisfy({
  subsets: ["latin"],
  variable: "--font-satisfy",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Social Media",
  description: "Generated by nguyenleavu",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.4.2/css/all.css"
        />

        <link
          rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.4.2/css/sharp-solid.css"
        />

        <link
          rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.4.2/css/sharp-regular.css"
        />

        <link
          rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.4.2/css/sharp-light.css"
        />
      </head>

      <body className={satisfy.variable}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}

export default RootLayout;
