import { Metadata } from "next";
import NewFeeds from "./NewFeeds";
import Suggested from "./Suggested";

export const metadata: Metadata = {
  title: "Social Media - Home",
  description: "Generated by nguyenleavu",
};

export default function Home() {
  return (
    <main className="w-full flex justify-center pt-6">
      <NewFeeds />
      <Suggested />
    </main>
  );
}
